
export const NigerianStatesAndCities = [
    { state: 'Abia', cities: ['Umuahia', 'Aba', 'Ohafia'] },
    { state: 'Adamawa', cities: ['Yola', 'Mubi', 'Numan'] },
    { state: 'Akwa Ibom', cities: ['Uyo', 'Eket', 'Ikot Ekpene'] },
    { state: 'Anambra', cities: ['Awka', 'Onitsha', 'Nnewi'] },
    { state: 'Bauchi', cities: ['Bauchi', 'Azare', 'Misau'] },
    { state: 'Bayelsa', cities: ['Yenagoa', 'Brass', 'Sagbama'] },
    { state: 'Benue', cities: ['Makurdi', 'Gboko', 'Otukpo'] },
    { state: 'Borno', cities: ['Maiduguri', 'Biu', 'Bama'] },
    { state: 'Cross River', cities: ['Calabar', 'Ikom', 'Ogoja'] },
    { state: 'Delta', cities: ['Asaba', 'Warri', 'Sapele'] },
    { state: 'Ebonyi', cities: ['Abakaliki', 'Afikpo', 'Onueke'] },
    { state: 'Edo', cities: ['Benin City', 'Auchi', 'Uromi'] },
    { state: 'Ekiti', cities: ['Ado-Ekiti', 'Ikere-Ekiti', 'Efon-Alaaye'] },
    { state: 'Enugu', cities: ['Enugu', 'Nsukka', 'Oji River'] },
    { state: 'Gombe', cities: ['Gombe', 'Kumo', 'Billiri'] },
    { state: 'Imo', cities: ['Owerri', 'Orlu', 'Okigwe'] },
    { state: 'Jigawa', cities: ['Dutse', 'Hadejia', 'Birnin Kudu'] },
    { state: 'Kaduna', cities: ['Kaduna', 'Zaria', 'Kafanchan'] },
    { state: 'Kano', cities: ['Kano', 'Wudil', 'Rano'] },
    { state: 'Katsina', cities: ['Katsina', 'Daura', 'Funtua'] },
    { state: 'Kebbi', cities: ['Birnin Kebbi', 'Argungu', 'Yauri'] },
    { state: 'Kogi', cities: ['Lokoja', 'Okene', 'Idah'] },
    { state: 'Kwara', cities: ['Ilorin', 'Offa', 'Jebba'] },
    { state: 'Lagos', cities: ['Ikeja', 'Lagos', 'Epe', 'Ikorodu'] },
    { state: 'Nasarawa', cities: ['Lafia', 'Keffi', 'Akwanga'] },
    { state: 'Niger', cities: ['Minna', 'Bida', 'Suleja'] },
    { state: 'Ogun', cities: ['Abeokuta', 'Ijebu-Ode', 'Sagamu'] },
    { state: 'Ondo', cities: ['Akure', 'Owo', 'Ondo Town'] },
    { state: 'Osun', cities: ['Osogbo', 'Ile-Ife', 'Ilesa'] },
    { state: 'Oyo', cities: ['Ibadan', 'Ogbomosho', 'Oyo'] },
    { state: 'Plateau', cities: ['Jos', 'Vom', 'Pankshin'] },
    { state: 'Rivers', cities: ['Port Harcourt', 'Bonny', 'Okrika'] },
    { state: 'Sokoto', cities: ['Sokoto', 'Wurno', 'Gwadabawa'] },
    { state: 'Taraba', cities: ['Jalingo', 'Wukari', 'Ibi'] },
    { state: 'Yobe', cities: ['Damaturu', 'Nguru', 'Gashua'] },
    { state: 'Zamfara', cities: ['Gusau', 'Kaura Namoda', 'Anka'] },
    { state: 'Federal Capital Territory', cities: ['Abuja'] },
];

    