export const ROLE_DASHBOARD_MAP: Record<string, string> = {
  Owner: '/owner',
  Planner: '/planner',
  Hotelier: '/hotelier',
  'Hall Owner': '/hall-owner',
  'Car Hire Service': '/car-hire',
  Ticketier: '/ticketier',
  'Co-host': '/cohost',
  Security: '/security',
  'MC/Host': '/vendor',
  Caterer: '/vendor',
  'DJ/Musician': '/vendor',
  'Fashion Designer': '/vendor',
  Photographer: '/vendor',
  Videographer: '/vendor',
  Vendor: '/vendor',
  'Super Admin': '/admin/super',
  'User Admin': '/admin/user',
  'Content Admin': '/admin/content',
  'Editorial Admin': '/admin/editorial',
};
