// This is a placeholder service worker file.
// The actual service worker will be generated by next-pwa.

import {precacheAndRoute} from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope;

self.addEventListener('install', () => {
    self.skipWaiting();
});

self.addEventListener('activate', (event) => {
    event.waitUntil(self.clients.claim());
});

// The precacheAndRoute function will be automatically replaced by next-pwa
// with the list of files to precache.
precacheAndRoute(self.__WB_MANIFEST);
